cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  name: ${NODE_NAME}
  ingest: ${NODE_INGEST}

processors: ${PROCESSORS:1}

network.host: ${NETWORK_HOST}

# path:
#   data: /data/data
#   logs: /data/log

bootstrap:
  memory_lock: ${MEMORY_LOCK}

http:
  enabled: ${HTTP_ENABLE}
  compression: true

discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    #minimum_master_nodes: ${NUMBER_OF_MASTERS}
discovery.zen.minimum_master_nodes: ${NUMBER_OF_MASTERS}
node.max_local_storage_nodes: 1

transport.host: ${TRANSPORT_HOST}

